services:
  #--- QUEUE AND STORAGE ---
  redis-local:
    image: redis:latest
    command: redis-server --save "" --appendonly no --maxclients 20000
    ports:
      - "6376:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "212MB"